### ISSUE TITLE
docker-compose 스터디

### ISSUE THREAD

**Issue by OkDoYun** [Musma/OJT-Backend#2]
## 개요
삼호 고소차 모니터링 프로젝트에 `docker compose`를 적용하기 위해 mysql과 node를 띄워보는 예제를 진행한다.

### 설치
일단 도커 컴포즈가 설치되었다는 가정하에 진행한다.
```shell
docker compose version
```
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

### 네트워크 생성
```shell
docker network create todo-app
```
```
9b497b4f77e455cc73cf789b1fe704779171713e92df0d95debd55f165368495
```

### mysql 컨테이너 실행
```shell
docker run -d --network todo-app --network-alias mysql -v todo-mysql-data:/
var/lib/mysql -e MYSQL_ROOT_PASSWORD=mysql -e MYSQL_DATABASE=todos mysql:5.7
```
- `-d`, `--detach`: Detached 모드, 데몬모드라고도하며 컨테이너가 백그라운드로 실행된다.
- `--network`: 컨테이너가 사용할 도커 네트워크를 지정한다.
- `--network-alias`: 대상 컨테이너가 놓이게 된 네트워크에 이름을 붙인다.
- `-v`, `--volume`: 볼륨을 설정한다. 호스트와 컨테이너의 디렉토리를 연결하여, 파일을 컨테이너에 저장하지  않고 호스트에 바로 저장(마운트)한다. 데이터베이스의 경우 컨테이너를 지웠다가 다시 띄워도 데이터가 남아있는 것을 기대할 수 있다.
- `-e`: 컨테이너내에서 사용할 환경변수를 지정한다.

```
Unable to find image 'mysql:5.7' locally
5.7: Pulling from library/mysql
9815334b7810: Pull complete
f85cb6fccbfd: Pull complete
b63612353671: Pull complete
447901201612: Pull complete
9b6bc806cc29: Pull complete
24ec1f4b3b0d: Pull complete
207ed1eb2fd4: Pull complete
27cbde3edd97: Pull complete
0a5aa35cc154: Pull complete
e6c92bf6471b: Pull complete
07b80de0d1af: Pull complete
Digest: sha256:c1bda6ecdbc63d3b0d3a3a3ce195de3dd755c4a0658ed782a16a0682216b9a48
Status: Downloaded newer image for mysql:5.7
8a73094ff549eda3c5fe2bd5586e8c2a79d330cf54bc1e851286cadef488538f
```

### 컨테이너 실행 확인
```shell
 docker exec -it 8a73094 mysql -p
```
- `<mysql-container-id>`: 끝까지 안적어줘도 가용 컨테이너중 식별이 가능하다면 유효하다.

```
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.39 MySQL Community Server (GPL)

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```
> 비밀번호는 아까 mysql로 설정했다.

```sql
show databases;
```
```
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
| todos              |
+--------------------+
5 rows in set (0.00 sec)
```
환경변수로 넣어준 데이터베이스 `todos`도 잘 생성되었다.

## 앱 준비
[해당 레포지토리](https://github.com/docker/getting-started)에서 앱을 가져온다.

가져온 레포의 `app/` 아래의 내용을 마운트하기 위해 경로를 이동한다.
```shell
cd getting-started-master/app
```

##  앱 컨테이너 실행
절대 경로 확인
```shell
PWD
```
```
/Users/ogdoyun/getting-started-master/app
```

```shell
docker run -dp 3000:3000 -w /app -v ${PWD}:/app --network todo-app -e MYSQL_HOST=mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=mysql -e MYSQL_DB=todos node:12-alpine sh -c "yarn install && yarn run dev"
```
> 레포지토리의 app안에 내용을 마운트했고 그 내용이 /app안으로 들어간다.
- `-w`, `--workdir`: 컨테이너 안의 프로세스가 실행될 디렉터리를 설정한다.
	- `/app`
- `-v`: 볼륨을 마운트하여 사용
	- `/Users/ogdoyun/getting-started-master/app:/app`
	- `<호스트의 디렉토리>:<컨테이너의 디렉토리>
- `-p`, `--publish`: 호스트로 컨테이너의 포트를 포워딩한다.
	- `<host-port>`:`<container-port>`
	- `-p 3000:3000`
```
c3ad83853bdacec6125914e511ca2f26ab87cdff346c4fddd95f2d239172daa9
```
```shell
docker logs c3ad83
```
```
yarn install v1.22.18
[1/4] Resolving packages...
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 110.66s.
yarn run v1.22.18
$ nodemon src/index.js
[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/index.js`
Waiting for mysql:3306.
Connected!
Connected to mysql db at host mysql
Listening on port 3000
```
mysql에 연결된 로그도 확인할 수 있다.

## 앱 확인
브라우저에서 `localhost:3000`으로 앱을 배포상태를 확인하고 데이터를 삽입한다.
마운트 경로, 삽입한 데이터 영속성을 확인한다.
```shell
docker exec -it 8a73094 mysql -p todos
```
```sql
select * from todo_items;
```
```
+--------------------------------------+------+-----------+
| id                                   | name | completed |
+--------------------------------------+------+-----------+
| c3d43c30-e8fa-48f5-9602-2391339786cd | hihi |         0 |
+--------------------------------------+------+-----------+
1 row in set (0.00 sec)
```

## 매커니즘

app 실행 시 아래의 코드가 실행된다.
```typescript
const {
    MYSQL_HOST: HOST,
    MYSQL_HOST_FILE: HOST_FILE,
    MYSQL_USER: USER,
    MYSQL_USER_FILE: USER_FILE,
    MYSQL_PASSWORD: PASSWORD,
    MYSQL_PASSWORD_FILE: PASSWORD_FILE,
    MYSQL_DB: DB,
    MYSQL_DB_FILE: DB_FILE,
} = process.env;

async function init() {
    const host = HOST_FILE ? fs.readFileSync(HOST_FILE) : HOST;
    const user = USER_FILE ? fs.readFileSync(USER_FILE) : USER;
    const password = PASSWORD_FILE ? fs.readFileSync(PASSWORD_FILE) : PASSWORD;
    const database = DB_FILE ? fs.readFileSync(DB_FILE) : DB;

    await waitPort({ host, port : 3306});
    ...
```
두 컨테이너 모두 같은 네트워크 위에 있다. -> `--network todo-app`
mysql 컨테이너를 실행시킬 때 네트워크 설정 -> `--network-alias mysql`
앱 컨테이너를 실행시킬 때 환경변수 설정 -> `-e MYSQL_HOST=mysql`

## Docker compose 구성

`app/`의 위치에서 `docker-compose.yaml`파일을 생성한다.
```shell
cd ./app
```
```shell
pwd
```
```
/Users/ogdoyun/getting-started-master/app
```
```shell
vi docker-compose.yaml
```

### 앱 컨테이너
```shell
docker run -dp 3000:3000 -w /app -v ${PWD}:/app --network todo-app -e MYSQL_HOST=mysql -e MYSQL_USER=root -e MYSQL_PASSWORD=mysql -e MYSQL_DB=todos node:12-alpine sh -c "yarn install && yarn run dev"
```
위 명령어를 `docker-compos`형식에 맞게 재구성

```yaml
version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DB: todos
```
> `yaml`파일형식은 들여쓰기가 중요하니 에디터에서 플러그인을 켜고 하자.

### mysql 컨테이너

위와 같이 아래의 명령어도 `docker-compos`형식에 맞게 재구성
```shell
docker run -d --network todo-app --network-alias mysql -v todo-mysql-data:/
var/lib/mysql -e MYSQL_ROOT_PASSWORD=mysql -e MYSQL_DATABASE=todos mysql:5.7
```

```yaml
version: "3.7"

services:
  app:
    # The app service definition
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
```

### 최종 결과
```yaml
version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
```
명령어들과 조금 다른 점은 `network`을 따로 지정해주지 않았다. app 이름으로 자동으로 생성되는 듯 하다.

## docker-compose 실행

기존의 docker 컨테이너들을 지운 후 진행한다.
```shell
docker-compose up -d
```
```
Creating network "app_default" with the default driver
Creating volume "app_todo-mysql-data" with default driver
Creating app_app_1   ... done
Creating app_mysql_1 ... done
```
`docker network(app_default)`와  `docker volume(app_todo-mysql-data)`가 기본으로 생성되는 모습을 볼 수 있다.

```shell
docker-compose logs app
```
```
Attaching to app_app_1
app_1    | yarn install v1.22.18
app_1    | [1/4] Resolving packages...
app_1    | warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^2.0.0"
app_1    | warning Resolution field "ansi-regex@5.0.1" is incompatible with requested version "ansi-regex@^3.0.0"
app_1    | success Already up-to-date.
app_1    | Done in 1.08s.
app_1    | yarn run v1.22.18
app_1    | $ nodemon src/index.js
app_1    | [nodemon] 2.0.13
app_1    | [nodemon] to restart at any time, enter `rs`
app_1    | [nodemon] watching path(s): *.*
app_1    | [nodemon] watching extensions: js,mjs,json
app_1    | [nodemon] starting `node src/index.js`
app_1    | Waiting for mysql:3306......
app_1    | Connected!
app_1    | Connected to mysql db at host mysql
app_1    | Listening on port 3000
```

mysql log를 확인 하려면 아래의 명령어로 하면된다.
```shell
docker-compose logs mysql
```

## 리소스 정리
```shell
docker-compose down
```
```
Stopping app_app_1   ... done
Stopping app_mysql_1 ... done
Removing app_app_1   ... done
Removing app_mysql_1 ... done
Removing network app_default
```
네트워크는 지워졌지만 볼륨은 지워지지 않는다.

볼륨도 같이 삭제하려면 아래의 명령어로 하면된다.
```shell
docker-compose down --volumes
```

> 주의) 예제를 따라하려면 기본적으로 app 디렉토리 아래에서 진행해야한다.
